dist: bionic
language: bash
sudo: required

before_install:
  - curl https://raw.githubusercontent.com/Jasstkn/otus-platform-tests/better-kubernetes-security/homeworks/kubernetes-security/run.sh | bash
