kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: bobRoleBiding
subjects:
  - kind: ServiceAccount
    name: bob
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io