helmDefaults:
  verify: false
  wait: true
  timeout: 600
  recreatePods: false
  force: false
  atomic: false
  tls: false

environments:
  infra:
    values:
      - "values/{{ .Environment.Name }}/charts-versions.yaml"
      - kubeContext: gke_infra-265919_us-central1_infra

repositories:
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor
    url: https://helm.goharbor.io

releases:
  - name: nginx-ingress
    chart: "stable/nginx-ingress"
    namespace: nginx-ingress
    version: {{ index .Environment.Values.version "nginx-ingress" }}
    missingFileHandler: Warn
    values:
      - "./values/{{ .Environment.Name }}/nginx-ingress.yaml"

  - name: cert-manager
    chart: jetstack/cert-manager
    namespace: cert-manager
    version: {{ index .Environment.Values.version "cert-manager" }}
    missingFileHandler: Warn
    values:
      - "./values/{{ .Environment.Name }}/cert-manager.yaml"

  - name: harbor
    chart: harbor/harbor
    namespace: harbor
    version: {{ index .Environment.Values.version "harbor" }}
    missingFileHandler: Warn
    values:
      - "./values/{{ .Environment.Name }}/harbor.yaml"

