controller:
  replicaCount: 3
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - nginx-ingress
        topologyKey: "kubernetes.io/hostname"

  tolerations:
  - key: node-role
    operator: Equal
    value: infra
    effect: NoSchedule